

###
GET http://localhost:3000/api/reparaciones


###
GET http://localhost:3000/api/reparaciones/2



###
GET http://localhost:3000/api/vehiculos

###
POST http://localhost:3000/api/clientes/tel
Content-Type: application/json

{
    "telefono":"611234567"
}


###
POST http://localhost:3000/api/clientes/mail
Content-Type: application/json

{
    "email":"miguel.rd@example.com"
}

###
POST http://localhost:3000/api/clientes/new
Content-Type: application/json

{
    "nombre":"Rafael",
    "apellidos":"Moreno Cortés",
    "dni":"09998765e",
    "telefono":"644567654",
    "email":"rafi@gmail.com",
    "direccion":"C/ Gran Vía 32, Madrid"
}

###
PUT http://localhost:3000/api/clientes/3
Content-Type: application/json

{
    "nombre":"Laura",
    "apellidos":"Díaz Cortés",
    "dni":"09978765e",
    "telefono":"640567654",
    "email":"raii@gmail.com",
    "direccion":"C/ Gran Vía 32, Madrid"
}

###
GET http://localhost:3000/api/clientes/5

###
GET http://localhost:3000/api/clientes



###
GET http://localhost:3000/api/usuarios

###
GET http://localhost:3000/api/usuarios/id
Content-Type: application/json

{
    "id": 1
}

###
POST http://localhost:3000/api/usuarios/tel
Content-Type: application/json

{
    "telefono": 600567890
}

###
POST http://localhost:3000/api/usuarios/email
Content-Type: application/json

{
    "email": "pedro.hernandez@example.com"
}

###
POST http://localhost:3000/api/vehiculos
Content-Type: application/json

{
    "matricula": "1234ABC"
}




